version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "3366:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=OmkPri@26
      - MYSQL_DATABASE=studentdb
    restart: always
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always
  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - db
    restart: always